artifacts_root : artifacts


data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://github.com/Shaiksaad/MLOPS_data_source/raw/main/wine_quality.zip
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_dir: artifacts/data_ingestion
